#!/bin/bash

dir=$(dirname "$0")

if [ ! -d "$dir"/env ]; then
    python3 -m venv "$dir"/env
    source "$dir"/env/bin/activate
    pip3 install python-escpos readchar pyusb
else
    source "$dir"/env/bin/activate
fi
# clear window
printf '\033[2J\033[3J\033[H'
# resize window
printf '\033[8;24;32t'
# set window title
printf '\033]0;R-TYPE\007'
python3 "$dir"/type.py

exit 0